name: Terraform Pipeline2
on: [ pull_request, push ]

jobs:
  ermetic:
    name: Ermetic
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Display file content
        run: cat results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif